---

apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  selector: 
    app: odoo
  ports:
  - name: http
    # port: 8069
    port: 80
    targetPort: 8069
  # type: NodePort
  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector: 
    app: db
  ports:
  - name: db
    port: 5432
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: odoo
  replicas: 1

  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: akhdaniel2/odoo-account:latest
        env:
        - name: HOST
          value: db
        volumeMounts:
        - name: odoo-web-pvc
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-web-pvc
        persistentVolumeClaim:
          claimName: odoo-web-pvc
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: db
  replicas: 1
  
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_DATABASE
          value: odoo
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: odoo-db-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: odoo-db-pvc
        persistentVolumeClaim:
          claimName: odoo-db-pvc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/pv0001/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-web-pvc
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


      
    